//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalClockIndexKST.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalClockIndexKST.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LibrarySnap {
            get {
                object obj = ResourceManager.GetObject("LibrarySnap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ... Pack a lunchbox and consume it on top of a trash can in the streets of District 11 at 1 PM today..
        /// </summary>
        internal static string Prescript1 {
            get {
                return ResourceManager.GetString("Prescript1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. On the morning after receiving the Prescript, drink three cups of water as soon as you get up..
        /// </summary>
        internal static string Prescript10 {
            get {
                return ResourceManager.GetString("Prescript10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. Race against residents that live in the same building as you to District 7. Measure the distance every twenty-three minutes and disqualify the one farthest away from the destination..
        /// </summary>
        internal static string Prescript11 {
            get {
                return ResourceManager.GetString("Prescript11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. Within three days, knit a scarf with a butterfly pattern..
        /// </summary>
        internal static string Prescript12 {
            get {
                return ResourceManager.GetString("Prescript12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. Dial any number. Give a New Year’s greetings and words of blessing to whoever receives the call..
        /// </summary>
        internal static string Prescript13 {
            get {
                return ResourceManager.GetString("Prescript13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. See green from a white wall..
        /// </summary>
        internal static string Prescript14 {
            get {
                return ResourceManager.GetString("Prescript14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. When hungry, consume a Cheeki’s cheeseburger with added onion..
        /// </summary>
        internal static string Prescript15 {
            get {
                return ResourceManager.GetString("Prescript15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. Fold thirty-nine paper cranes and throw them from the rooftop..
        /// </summary>
        internal static string Prescript16 {
            get {
                return ResourceManager.GetString("Prescript16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. At work, cut the ear of the first person to fulminate against you..
        /// </summary>
        internal static string Prescript17 {
            get {
                return ResourceManager.GetString("Prescript17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. When your eyes meet another person’s, nod at them..
        /// </summary>
        internal static string Prescript18 {
            get {
                return ResourceManager.GetString("Prescript18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. Return to your home this instant. You may leave once a dog barks in front of your house one time..
        /// </summary>
        internal static string Prescript19 {
            get {
                return ResourceManager.GetString("Prescript19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. Bake dacquoise while the hour hand rests between 7 and 8, and eat it while watching a movie..
        /// </summary>
        internal static string Prescript2 {
            get {
                return ResourceManager.GetString("Prescript2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. Wear light green clothing and take 10 steps in a triangle-shaped alley..
        /// </summary>
        internal static string Prescript20 {
            get {
                return ResourceManager.GetString("Prescript20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. Initiate a game of Never Have I Ever with the first five people you encounter. When one folds a finger, break it..
        /// </summary>
        internal static string Prescript3 {
            get {
                return ResourceManager.GetString("Prescript3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. Neatly clip the nails of the sixty-second person you come across..
        /// </summary>
        internal static string Prescript4 {
            get {
                return ResourceManager.GetString("Prescript4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. Pet quadrupedal animals five times..
        /// </summary>
        internal static string Prescript5 {
            get {
                return ResourceManager.GetString("Prescript5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. Spin a wheel and throw a cake at the person determined by the result..
        /// </summary>
        internal static string Prescript6 {
            get {
                return ResourceManager.GetString("Prescript6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. Consume eight crabs stored at room temperature and ripe persimmon at once..
        /// </summary>
        internal static string Prescript7 {
            get {
                return ResourceManager.GetString("Prescript7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. At the railing on the roof of a building, shout out the name of the person you dislike, then jump off. The height of the building does not matter..
        /// </summary>
        internal static string Prescript8 {
            get {
                return ResourceManager.GetString("Prescript8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To …. After a meal, discard all dishes that were used to serve it..
        /// </summary>
        internal static string Prescript9 {
            get {
                return ResourceManager.GetString("Prescript9", resourceCulture);
            }
        }
    }
}
